name: CMake (Ubuntu Linux)

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest
    container: mrts/qt-cmake-gtest-valgrind-ubuntu:v1.8

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -S . -B build

    - name: Build
      run: cmake --build build --config $BUILD_TYPE

    - name: Test
      run: ctest -V -C $BUILD_TYPE --test-dir build
