name: CMake (Fedora Linux)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.container == 'fedora:rawhide' }}
    strategy:
      matrix:
        container: ['fedora:latest', 'fedora:rawhide']
        build_type: [Release, RelWithDebInfo]

    container:
      image: ${{ matrix.container }}

    steps:
    - name: Install dependencies
      run: dnf install -y --setopt=install_weak_deps=False git gcc-c++ cmake gtest-devel openssl-devel pcsc-lite-devel

    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S . -B build

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} -j $(nproc)

    - name: Test
      run: ctest -V -C ${{ matrix.build_type }} --test-dir build
